apiVersion: v1
kind: Service
metadata:
  name: audit
  namespace: sis
  labels:
    app: audit
spec:
  type: ClusterIP
  selector:
    app: audit
  ports:
  - name: http
    port: 3005
    targetPort: 3005
