apiVersion: v1
kind: Service
metadata:
  name: enrollment
  namespace: sis
  labels:
    app: enrollment
spec:
  type: ClusterIP
  selector:
    app: enrollment
  ports:
  - name: http
    port: 3003
    targetPort: 3003
