apiVersion: v1
kind: Service
metadata:
  name: identity
  namespace: sis
  labels:
    app: identity
spec:
  type: ClusterIP
  selector:
    app: identity
  ports:
  - name: http
    port: 3000
    targetPort: 3000
